### ISSUE TITLE
Bug: getChangingDimension parameters

### ISSUE THREAD

**Issue by NguyenJohnnyT** [dmartin4820/react-phys-color#14]
* Current logic for `getChangingDimension` can only accept incrementing rgb values for the `from` and `to` parameters
* For example:
* INCORRECT: `from = { r: 200, g: 0, b: 0, a: 1 }` && `to = { r: 0, g: 0, b: 0, a: 1 }`
* CORRECT: `from = { r: 0, g: 0, b: 0, a: 1 }` && `to = { r: 200, g: 0, b: 0, a: 1 }`

I inadvertently made this mistake while testing out `userOptions.colorRange` from and to keys.

**Comment by dmartin4820** [comment]
Resolved by throwing error if 'delta' is negative
